# -*- coding: utf-8 -*-
"""TASK 1 hangmangame

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLgnpqkVd6jFFQxN-Faa3KAY9KsSlc49
"""

import random

WORDS = ["python", "computer", "programming", "developer", "database"]
MAX_WRONG_GUESSES = 6


def play_game():
    secret_word = random.choice(WORDS)
    guessed_letters = set()
    wrong_guesses = 0

    print("\n=== CodeAlpha Hangman Game ===")
    print("Guess the word one letter at a time.")
    print(f"You can make {MAX_WRONG_GUESSES} wrong guesses.\n")

    while wrong_guesses < MAX_WRONG_GUESSES:
        display_word = " ".join(
            letter if letter in guessed_letters else "_"
            for letter in secret_word
        )

        print("Word:", display_word)

        if all(letter in guessed_letters for letter in secret_word):
            print("Congratulations! You guessed the word:", secret_word)
            return

        guess = input("Enter one letter: ").strip().lower()

        if len(guess) != 1 or not guess.isalpha():
            print("Please enter exactly one alphabet letter.\n")
            continue

        if guess in guessed_letters:
            print("You already guessed that letter.\n")
            continue

        guessed_letters.add(guess)

        if guess in secret_word:
            print("Correct guess!\n")
        else:
            wrong_guesses += 1
            print(
                f"Wrong guess! Remaining attempts: "
                f"{MAX_WRONG_GUESSES - wrong_guesses}\n"
            )

    print("Game over! The word was:", secret_word)


if __name__ == "__main__":
    play_game()